- utility-emissions-channel/chaincode/go/emissioncc.go
- utility-emissions-channel/chaincode/go/go.mod
getEmissionRecord based on UtilityID
> getEmissionRecord based on UtilityID

- utility-emissions-channel/docker-compose-setup/DEPLOY.md
Signed-off-by: Jeremy Wickersheimer <jwickers@gmail.com>
> Cleanup doc and add permission fixes

- README.md
Signed-off-by: Si Chen <sichen@opensourcestrategies.com>
> trivial change

- multi-cloud-deplyoment/README.md
- multi-cloud-deplyoment/deploy-digitalocean/fabric-ca-deplyoment.yaml
- multi-cloud-deplyoment/deploy-digitalocean/ingress-fabric-services-deploy.yaml
- multi-cloud-deplyoment/deploy-digitalocean/kubernetes-ingress-controller-deploy.yaml
- multi-cloud-deplyoment/fabric-config/fabric-ca-server-config.yaml
- multi-cloud-deplyoment/registerEnroll.sh
Started working on the multi-cloud deployment and finished with the first steps.
The pull request doesn't affect any of our previous work.
> initial commit

- .gitignore
Signed-off-by: Ry Jones <ry@linux.com>
> Update .gitignore, remove binary files

- multi-cloud-deployment/README.md
Fix multi-cloud-deployment project `README.md` file link broken.
> docs: fix docs link broken

- utility-emissions-channel/chaincode/typescript/.dockerignore
- utility-emissions-channel/chaincode/typescript/.gitignore
- utility-emissions-channel/chaincode/typescript/Dockerfile
- utility-emissions-channel/chaincode/typescript/package.json
- utility-emissions-channel/chaincode/typescript/src/index.ts
- utility-emissions-channel/chaincode/typescript/src/lib/emissions-calc.ts
- utility-emissions-channel/chaincode/typescript/src/lib/emissions.ts
- utility-emissions-channel/chaincode/typescript/src/lib/emissionsRecordContract.ts
- utility-emissions-channel/chaincode/typescript/src/lib/utilityEmissionsFactor.ts
- utility-emissions-channel/chaincode/typescript/src/lib/utilityLookupItem.ts
- utility-emissions-channel/chaincode/typescript/src/util/const.ts
- utility-emissions-channel/chaincode/typescript/src/util/state.ts
- utility-emissions-channel/chaincode/typescript/src/util/util.ts
- utility-emissions-channel/chaincode/typescript/src/util/worldstate.ts
- utility-emissions-channel/chaincode/typescript/test/lib/emissions-calc.test.ts
- utility-emissions-channel/chaincode/typescript/test/lib/utilityEmissionsFactor.test.ts
- utility-emissions-channel/chaincode/typescript/tsconfig.json
- utility-emissions-channel/chaincode/typescript/tslint.json
- /src
- /src/lib
- /src/util
- /test
- /test/lib
[issue_47](https://github.com/hyperledger-labs/blockchain-carbon-accounting/issues/47)
> Resolving Issue 47

- net-emissions-token-network/docs/using-the-contracts.md
Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>
> docs(net-emissions-token-network): fix typo "addresse"

- multi-cloud-deployment/network-artifacts/configtx.yaml
Signed-off-by: udosson <r.klemens@yahoo.de>
> added opensolarx

- utility-emissions-channel/README.md
- utility-emissions-channel/docker-compose-setup/docker/nodes/node-one/docker-compose-chaincode.yaml
- utility-emissions-channel/docker-compose-setup/docker/nodes/node-two/docker-compose-chaincode.yaml
- utility-emissions-channel/docker-compose-setup/egrid-data-loader.js
- utility-emissions-channel/docker-compose-setup/scripts/envVar.sh
- utility-emissions-channel/docker-compose-setup/scripts/installChaincode.sh
- utility-emissions-channel/docker-compose-setup/scripts/invokeChaincode.sh
- utility-emissions-channel/typescript_app/runTests.sh
- utility-emissions-channel/typescript_app/src/blockchain-gateway/utilityEmissionsChannel/emissionsContractInvoke.ts
- utility-emissions-channel/typescript_app/tests/test.js
Signed-off-by: Pihu1998 pranamika.pihu1998@gmail.com
This PR is to fix all the bugs to get all the automation tests working in utility-emissions-channel.
Relevant Commit:
The last commit: `Fix for all automation tests` gets all the tests working.
> Fixes bugs for automation tests

- utility-emissions-channel/README.md
- utility-emissions-channel/docker-compose-setup/egrid-data-loader.js
- utility-emissions-channel/docker-compose-setup/scripts/envVar.sh
- utility-emissions-channel/docker-compose-setup/scripts/installChaincode.sh
- utility-emissions-channel/docker-compose-setup/scripts/invokeChaincode.sh
This PR is to fix all the bugs occurring  to get the utility-emissions-channel up and running.
**1st Commit:**
- Fixes the Null values in data array obtained from parsing XLSX files.
> Fixes bugs to get utility-emissions-channel up and running #98

- utility-emissions-channel/docker-compose-setup/docker/nodes/node-one/docker-compose-chaincode.yaml
- utility-emissions-channel/docker-compose-setup/docker/nodes/node-two/docker-compose-chaincode.yaml
- utility-emissions-channel/typescript_app/runTests.sh
- utility-emissions-channel/typescript_app/src/blockchain-gateway/utilityEmissionsChannel/emissionsContractInvoke.ts
The commits are in regard to a fix for the build errors in the utility-emissions-channel
> Fix to build errors

- utility-emissions-channel/README.md
Signed-off-by: Si Chen <sichen@opensourcetrategies.com>
> fix instructions to query results

- utility-emissions-channel/docker-compose-setup/scripts/envVar.sh
Signed-off-by: Si Chen <sichen@opensourcetrategies.com>
> Fix bug causing invoke chain code to fail.  Thanks to Pritam @zzocker

- utility-emissions-channel/README.md
Signed-off-by: Si Chen <sichen@opensourcetrategies.com>
> fix incorrect couchdb database name

- utility-emissions-channel/README.md
- utility-emissions-channel/docker-compose-setup/egrid-data-loader.js
> Loading new egrid database records

- utility-emissions-channel/README.md
- utility-emissions-channel/docker-compose-setup/egrid-data-loader.js
- utility-emissions-channel/typescript_app/automated-tests.sh
> Moving automated tests to run outside of api container

- utility-emissions-channel/typescript_app/README.md
- utility-emissions-channel/typescript_app/app.ts
- utility-emissions-channel/typescript_app/src/config/ledger-config.ts
> updated README and added support for ropsten

- utility-emissions-channel/docker-compose-setup/egrid-data-loader.js
> Fixing NERC 2019 Data Loader 'undefined' bug

- utility-emissions-channel/typescript_app/package.json
> fix(typescript_app): fixed web3 version

- utility-emissions-channel/chaincode/typescript/src/index.ts
- utility-emissions-channel/chaincode/typescript/src/lib/emissionsRecordContract.ts
- utility-emissions-channel/typescript_app/app.ts
- utility-emissions-channel/typescript_app/src/blockchain-gateway/I-utilityEmissionsChannel.ts
- utility-emissions-channel/typescript_app/src/blockchain-gateway/ledger-integration.ts
- utility-emissions-channel/typescript_app/src/blockchain-gateway/netEmissionsTokenNetwork.ts
- utility-emissions-channel/typescript_app/src/blockchain-gateway/utilityEmissionsChannel.ts
- utility-emissions-channel/typescript_app/src/blockchain-gateway/utils/dateUtils.ts
- utility-emissions-channel/typescript_app/src/config/ledger-config.ts
- utility-emissions-channel/typescript_app/src/routers/carbonAccounting.ts
> feat(utilityCC): update tokenId of audited Emission tokens in batch

- utility-emissions-channel/docker-compose-setup/docker/application/config.json
- utility-emissions-channel/docker-compose-setup/docker/application/docker-compose.yaml
- utility-emissions-channel/docker-compose-setup/scripts/startApi.sh
- utility-emissions-channel/typescript_app/app.ts
- utility-emissions-channel/typescript_app/package-lock.json
- utility-emissions-channel/typescript_app/package.json
- utility-emissions-channel/typescript_app/src/blockchain-gateway/I-fabricRegistry.ts
- utility-emissions-channel/typescript_app/src/blockchain-gateway/fabricRegistry.ts
- utility-emissions-channel/typescript_app/src/blockchain-gateway/ledger-integration.ts
- utility-emissions-channel/typescript_app/src/config/ledger-config.ts
- utility-emissions-channel/typescript_app/src/routers/carbonAccounting.ts
- utility-emissions-channel/typescript_app/src/routers/fabricRegistry.ts
- utility-emissions-channel/typescript_app/src/routers/utilityEmissionsChannel.ts
- utility-emissions-channel/typescript_app/swagger.json
- start utility api using `./start.sh`
- made swagger work
> fix(utility_app): start api with docker, fixed swagger

- utility-emissions-channel/docker-compose-setup/scripts/startApi.sh
- utility-emissions-channel/typescript_app/src/blockchain-gateway/ledger-integration.ts
> fix(utilityAPI): ./start.sh on local machine

- utility-emissions-channel/typescript_app/src/blockchain-gateway/netEmissionsTokenNetwork.ts
- utility-emissions-channel/typescript_app/src/routers/carbonAccounting.ts
> fix: made automaticRetireDate as optional parmas

- utility-emissions-channel/typescript_app/.env
- utility-emissions-channel/typescript_app/src/blockchain-gateway/ledger-integration.ts
- utility-emissions-channel/typescript_app/src/blockchain-gateway/utilityEmissionsChannel.ts
- utility-emissions-channel/typescript_app/src/blockchain-gateway/utils/aws.ts
- utility-emissions-channel/typescript_app/src/config/aws-config.ts
- utility-emissions-channel/typescript_app/src/routers/utilityEmissionsChannel.ts
> feat(typescript_app): added saving of emisions records in S3

- utility-emissions-channel/docker-compose-setup/egrid-data-loader.js
> Fix for RES_proxies_EEA data loader

- utility-emissions-channel/docker-compose-setup/scripts/fabricNetwork.sh
> fix fabric network reset script

- .gitignore
> ignored code.tar.gz and *.chaincode.tgz

- utility-emissions-channel/typescript_app/swagger.json
OpenAPI version 3.0.0 is used but, definitions and schemas were defined for version 2. 
> bug fix to typescript_app swagger spec

- secure-identities/identity-ui/README.md
- secure-identities/identity-ui/package.json
- secure-identities/vault-identity/test/setup.ts
fixed small typo fix in `vault-identity` and `identity-ui`
> typeo_fix: fixed in vault-identity and identity-ui

- .github/workflows/ci.yml
- .github/workflows/test-report.yml
Added in-line comments to the YAML workflow files for the CI pipeline. Closes #307.
> docs(CI): Add comments for CI pipeline

- net-emissions-token-network/contracts/NetEmissionsTokenNetwork.sol
- net-emissions-token-network/interface/packages/react-app/src/components/access-control-form.js
- net-emissions-token-network/interface/packages/react-app/src/components/dashboard.js
- net-emissions-token-network/interface/packages/react-app/src/components/issue-form.js
- net-emissions-token-network/interface/packages/react-app/src/services/contract-functions.js
- net-emissions-token-network/test/token-network-integration-tests.js
Assigning roles is not working yet but you can issue tokens and see them.
> Initial UI for carbon tracker 

- renovate.json
- supply-chain/.env.SAMPLE
- supply-chain/README.md
- supply-chain/package.json
- supply-chain/ups.js
This will let you calculate the travel distance of UPS package with its tracking number.
> initial supply chain emissions calculation: distance of UPS package by tracking number.

- supply-chain/ups.js
Signed-off-by: Jeremy Wickersheimer <jwickers@gmail.com>
> Calculate estimated emissions -- placeholder

- data/.gitignore
- data/README.md
- data/loadData.sh
- data/src/dataLoader.ts
- data/src/models.ts
- data/src/models/oilAndGasAsset.ts
- data/src/postgresDbService.ts
- data/src/repositories/oilAndGasAsset.repo.ts
- lib/data-common/db.ts
- lib/data-common/spreadsheetImport.ts
- lib/oil-and-gas-data/package.json
- lib/oil-and-gas-data/src/oilAndGasAsset.ts
- lib/oil-and-gas-data/tsconfig.json
- package-lock.json
This commit adds data schema for oil-and-gas-asset data and data loader script to load U.S. well data from [HILFD](https://hifld-geoplatform.opendata.arcgis.com/datasets/geoplatform::oil-and-natural-gas-wells/explore?location=30.073392%2C-95.254322%2C4.00)
> data schema and loader for U.S. oil & gas assets

- app/frontend/contracts/src/addresses.ts
Signed-off-by: Jameson Hodge <contact@jamesonhodge.com>
> Add Avalanche testnet contract addresses to frontend

- data/package.json
- data/src/api/postgresApi.ts
- package-lock.json
Signed-off-by: Achintya Kumar <ackintya@gmail.com>
> postgres emissionfactorApi 

- .env.SAMPLE
- app/api-server/components/event.listener.ts
- lib/blockchain-gateway/src/blockchain-gateway/config.ts
Signed-off-by: Jameson Hodge <contact@jamesonhodge.com>
> Support avalanche testnet for api-server and blockchain-gateway

- hardhat/hardhat.config.ts
Signed-off-by: Jameson Hodge <contact@jamesonhodge.com>
> create `grantAdminRole` hardhat task 

- hardhat/hardhat.config.ts
To use, run `npx hardhat roles` in the hardhat directory
> create hardhat roles task for NetEmissionsTokenNetwork

- hardhat/bevel/README.md
- hardhat/bevel/network.yaml
Signed-off-by: adityajoshi12 <adityaprakashjoshi1@gmail.com>
**Changes**
- Added steps and network configuration for deploying besu network using bevel
**Linked Issue**
#631
> Added deployment steps for besu network

- hardhat/bevel/local/README.md
- hardhat/bevel/local/kind.yaml
- hardhat/bevel/local/network.yaml
Signed-off-by: adityajoshi12 <adityaprakashjoshi1@gmail.com>
This PR contains documentation required for setting up the besu network locally.
#647
> added documentation from besu local setup

- hardhat/solidity/CarbonTracker.sol
Signed-off-by: brioux <Bertrand.rioux@gmail.com>
> Use tx.origin as issuedFrom address of tracker tokenTypedId=1

- data/oil_and_gas/README.md
Reference solution to error reported in [Issue 666 ](https://github.com/hyperledger-labs/blockchain-carbon-accounting/issues/666)
> Update Readme for oil and gas data loader
